<a href="https://colab.research.google.com/github/sabumjung/Machine-Learning-Algorithm/blob/master/ch03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# scikit-learn 토이 데이터셋

In [0]:
from sklearn.datasets import load_boston

In [0]:
boston = load_boston()
X = boston.data
Y = boston.target

In [34]:
print(X.shape)

(10, 2)


In [33]:
print(Y.shape)

(10, 1)


# 훈련 및 테스트 집합 만들기 

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=1000)

In [35]:
print(X_train.shape, X_test.shape)

(379, 13) (127, 13)


In [36]:
print(Y_train.shape, Y_test.shape)

(379,) (127,)


In [0]:
from sklearn.utils import check_random_state
rs = check_random_state(1000)

In [0]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=rs)

In [37]:
print(X_train.shape, X_test.shape)

(379, 13) (127, 13)


In [38]:
print(Y_train.shape, Y_test.shape)

(379,) (127,)


# 범주형 데이터 관리

In [39]:
import numpy as np
X = np.random.uniform(0.0, 1.0, size=(10, 2))
Y = np.random.choice(('Male','Female'), size=(10))
print(X[0], Y[0])

[0.5783514  0.89983477] Female


In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
yt = le.fit_transform(Y)
print(yt)

[0 0 1 1 0 0 0 1 1 0]


In [40]:
print(le.classes_)

['Female' 'Male']


In [30]:
output = [1, 0, 1, 1, 0, 0]
decoded_output = [le.classes_[i] for i in output]
print(decoded_output)

['Male', 'Female', 'Male', 'Male', 'Female', 'Female']


In [47]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
Yb = lb.fit_transform(Y)
print(Yb)

[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [48]:
lb.inverse_transform(Yb)

array(['Female', 'Female', 'Female', 'Female', 'Male', 'Male', 'Male',
       'Male', 'Male', 'Male'], dtype='<U6')

In [0]:
data = [
  { 'feature_1': 10.0, 'feature_2': 15.0 },
  { 'feature_1': -5.0, 'feature_3': 22.0 },
  { 'feature_3': -2.0, 'feature_4': 10.0 }
]

In [0]:
from sklearn.feature_extraction import DictVectorizer, FeatureHasher
dv = DictVectorizer()

In [45]:
Y_dict = dv.fit_transform(data)
Y_dict.todense()

matrix([[10., 15.,  0.,  0.],
        [-5.,  0., 22.,  0.],
        [ 0.,  0., -2., 10.]])

In [49]:
dv.vocabulary_

{'feature_1': 0, 'feature_2': 1, 'feature_3': 2, 'feature_4': 3}

In [52]:
fh = FeatureHasher()
Y_hashed = fh.fit_transform(data)
Y_hashed.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [0]:
from sklearn.preprocessing import OneHotEncoder
data = [
  [0, 10],
  [1, 11],
  [1, 8],
  [0, 12],
  [0, 15]
  ]

In [58]:
oh = OneHotEncoder(categorical_features=[0])
Y_oh = oh.fit_transform(data)
Y_oh.todense()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


matrix([[ 1.,  0., 10.],
        [ 0.,  1., 11.],
        [ 0.,  1.,  8.],
        [ 1.,  0., 12.],
        [ 1.,  0., 15.]])