<a href="https://colab.research.google.com/github/sabumjung/Machine-Learning-Algorithm/blob/master/ch03_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 음수 미포함 행렬 분해

In [0]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.decomposition import NMF

# For reproducibility
np.random.seed(1000)

In [3]:
# Load iris dataset
iris = load_iris()
print('Irid dataset shape')
print(iris.data.shape)

Irid dataset shape
(150, 4)


In [0]:
# Perform a non-negative matrix factorization
nmf = NMF(n_components=3, init='random', l1_ratio=0.1)
Xt = nmf.fit_transform(iris.data)

In [5]:
print('Reconstruction error')
print(nmf.reconstruction_err_)

Reconstruction error
1.89005254205774


In [6]:
print('Original Iris sample')
print(iris.data[0])

Original Iris sample
[5.1 3.5 1.4 0.2]


In [7]:
print('Compressed Iris sample (via Non-Negative Matrix Factorization)')
print(Xt[0])

Compressed Iris sample (via Non-Negative Matrix Factorization)
[1.23270986 1.11728116 0.10824566]


In [8]:
print('Rebuilt sample')
print(nmf.inverse_transform(Xt[0]))

Rebuilt sample
[5.10030776 3.49993422 1.40034931 0.19884065]
