<a href="https://colab.research.google.com/github/sabumjung/Machine-Learning-Algorithm/blob/master/ch11_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 모델-기반 협업 필터링

In [0]:
import numpy as np

from scipy.linalg import svd

In [0]:
# For reproducibility
np.random.seed(1000)

In [23]:
# Create a dummy user-item matrix
M = np.random.randint(0, 6, size=(20, 10))

print('User-Item matrix:')
print(M)

# Decompose M
U, s, V = svd(M, full_matrices=True)
S = np.diag(s)

print('U -> %r' % str(U.shape))
print('S -> %r' % str(S.shape))
print('V -> %r' % str(V.shape))

# Select the first 8 singular values
Uk = U[:, 0:8]
Sk = S[0:8, 0:8]
Vk = V[0:8, :]

# Compute the user and product vectors
Su = Uk.dot(np.sqrt(Sk).T)
Si = np.sqrt(Sk).dot(Vk).T

# Compute the average rating per user
Er = np.mean(M, axis=1)

# Perform a prediction for the user 5 and item 2
r5_2 = Er[5] + Su[5].dot(Si[2])
print(r5_2)

User-Item matrix:
[[3 0 3 4 1 5 0 1 5 0]
 [1 4 3 4 4 5 2 2 1 4]
 [4 2 1 0 2 4 4 5 2 4]
 [5 5 2 5 5 4 3 4 3 0]
 [4 2 5 2 4 0 4 4 3 1]
 [3 3 0 5 2 1 3 3 1 5]
 [5 3 4 5 3 0 0 2 2 5]
 [3 1 2 2 3 3 5 0 4 1]
 [0 1 1 0 0 0 2 3 1 5]
 [3 2 1 2 1 5 0 3 5 1]
 [4 3 3 3 4 3 5 0 1 3]
 [5 5 5 2 0 4 5 4 1 5]
 [5 5 1 4 1 4 5 0 2 1]
 [0 4 3 2 0 3 0 5 3 0]
 [4 3 3 3 3 5 4 4 2 4]
 [3 4 2 4 1 4 2 3 1 0]
 [5 4 4 4 3 5 4 2 1 0]
 [0 1 1 1 5 0 0 4 2 2]
 [1 2 0 4 2 0 1 1 1 3]
 [5 4 5 4 4 0 1 1 4 3]]
U -> '(20, 20)'
S -> '(10, 10)'
V -> '(10, 10)'
2.3884872011203746
