[View in Colaboratory](https://colab.research.google.com/github/sabumjung/Machine-Learning-Algorithm/blob/master/ch3.ipynb)

In [88]:
#원서 45 : toy datasets가져오기
from sklearn.datasets import load_boston
boston=load_boston()
X=boston.data
Y=boston.target
print(X.shape, Y.shape)

(506, 13) (506,)


In [89]:
#원서 47 : training와 test 데이터셋 만들기
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=1000)
print(X.shape, X_train.shape, Y_train.shape, X_test.shape, Y_test.shape)
print("훈련용 데이터 비율 : ", len(X_train)/len(X))

(506, 13) (379, 13) (379,) (127, 13) (127,)
훈련용 데이터 비율 :  0.7490118577075099


In [90]:
#원서 47 : training와 test 데이터셋 만들기
from sklearn.utils import check_random_state
rs=check_random_state(1000)
print(rs)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=rs)
print("테스트용 데이터 비율 : ", len(X_test)/len(X))

테스트용 데이터 비율 :  0.2509881422924901


In [91]:
#원서 48 : 이산형 데이터 관리
import numpy as np
#
X=np.random.uniform(0.0, 1.0, size=(10,2))
Y=np.random.choice(('Male', 'Female'), size=(10))
print(X[0])
print(Y[0])

[0.20819009 0.38944212]
Female


In [130]:
#원서 48 : 이산형 데이터 관리
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
yt=le.fit_transform(Y)
print(yt)

le.fit(['Female', 'Male'])
le.classes_

[0 1 0 0 1 0 0 0 1 1]


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array(['Female', 'Male'], dtype='<U6')

In [106]:
#원서 48 : 이산형 데이터 관리
output=[1, 0, 1, 1, 0, 0]
decoded_output=[le.classes_[i] for i in output]
print(decoded_output)

['Male', 'Female', 'Male', 'Male', 'Female', 'Female']


In [111]:
#원서 48 : 이산형 데이터 관리
from sklearn.preprocessing import LabelBinarizer
lb=LabelBinarizer()
Yb=lb.fit_transform(Y)
print(Yb)
lb.inverse_transform(Yb)

[[0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]]


array(['Female', 'Male', 'Female', 'Female', 'Male', 'Female', 'Female',
       'Female', 'Male', 'Male'], dtype='<U6')

In [127]:
import numpy as np
print(Y)
Y=lb.fit_transform(Y)
print(Y)

# print(Y[0])
# Yp=model.predict(X[0])
# print(Yp)
# Ypr=np.round(Yp)
# print(Ypr)
# lb.inverse_transform(Ypr)

[[0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]]
[[0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]]


In [116]:
Yp=model.predict(X[0])
Ypr=np.round(Yp)
lp.inverse_transform(Ypr)

ValueError: ignored