[View in Colaboratory](https://colab.research.google.com/github/sabumjung/Machine-Learning-Algorithm/blob/master/ch3.ipynb)

In [28]:
#원서 45 : toy datasets가져오기
from sklearn.datasets import load_boston
boston=load_boston()
X=boston.data
Y=boston.target
print(X.shape, Y.shape)

(506, 13) (506,)


In [29]:
#원서 47 : training와 test 데이터셋 만들기
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=1000)
print(X.shape, X_train.shape, Y_train.shape, X_test.shape, Y_test.shape)
print("훈련용 데이터 비율 : ", len(X_train)/len(X))

(506, 13) (379, 13) (379,) (127, 13) (127,)
훈련용 데이터 비율 :  0.7490118577075099


In [30]:
#원서 47 : training와 test 데이터셋 만들기
from sklearn.utils import check_random_state
rs=check_random_state(1000)
print(rs)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=rs)
print("테스트용 데이터 비율 : ", len(X_test)/len(X))

테스트용 데이터 비율 :  0.2509881422924901


In [31]:
#원서 48 : 이산형 데이터 관리
import numpy as np
X=np.random.uniform(0.0, 1.0, size=(10,2))
Y=np.random.choice(('Male', 'Female'), size=(10))
print(X[0])
print(Y[0])

[0.9870994  0.10141285]
Female


In [32]:
#원서 48 : 이산형 데이터 관리
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
yt=le.fit_transform(Y)
print(yt)

le.classes_

[0 0 1 1 0 1 0 0 0 1]


array(['Female', 'Male'], dtype='<U6')

In [33]:
#원서 48 : 이산형 데이터 관리
output=[1, 0, 1, 1, 0, 0]
decoded_output=[le.classes_[i] for i in output]
print(decoded_output)

['Male', 'Female', 'Male', 'Male', 'Female', 'Female']


In [36]:
#원서 48 : 이산형 데이터 관리
from sklearn.preprocessing import LabelBinarizer
#Binarizer는 기준값(threshold)값을 기준으로 결과를 0, 1로 구분한다. 디폴트 기준값은 0 이다.
lb=LabelBinarizer()
Yb=lb.fit_transform(Y)
print(Yb)
lb.inverse_transform(Yb)

[[0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]]


array(['Female', 'Female', 'Male', 'Male', 'Female', 'Male', 'Female',
       'Female', 'Female', 'Male'], dtype='<U6')

In [39]:
import numpy as np

Y=lb.fit_transform(Y)
print(Y)

[[0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]]


In [40]:
Yp=model.predict(X[0])
print(Yp)

NameError: ignored

In [41]:
Ypr=np.round(Yp)
print(Ypr)

NameError: ignored

In [42]:
lb.inverse_transform(Ypr)

NameError: ignored

In [0]:
Yp=model.predict(X[0])
Ypr=np.round(Yp)
lp.inverse_transform(Ypr)

ValueError: ignored

In [48]:
#원서 50
data=[
    {'feature_1':10.0, 'feature_2':15.0},
    {'feature_1':-5.0, 'feature_3':22.0},
    {'feature_3':-2.0, 'feature_4':10.0}
]

from sklearn.feature_extraction import DictVectorizer, FeatureHasher
dv=DictVectorizer()
Y_dict=dv.fit_transform(data)
Y_dict.todense()

matrix([[10., 15.,  0.,  0.],
        [-5.,  0., 22.,  0.],
        [ 0.,  0., -2., 10.]])

In [51]:
dv.vocabulary_

{'feature_1': 0, 'feature_2': 1, 'feature_3': 2, 'feature_4': 3}

In [0]:
fh=FeatureHasher()
Y_hashed=fh.fit_transform(data)

In [53]:
Y_hashed.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [0]:
#원서 50
from sklearn.preprocessing import OneHotEncoder

data=[
    [0,10],
    [1,11],
    [1,8],
    [0,12],
    [0,15]
]

In [58]:
oh=OneHotEncoder(categorical_features=[0])
print(oh)
Y_oh=oh.fit_transform(data)

OneHotEncoder(categorical_features=[0], dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)


In [57]:
Y_oh.todense()

matrix([[ 1.,  0., 10.],
        [ 0.,  1., 11.],
        [ 0.,  1.,  8.],
        [ 1.,  0., 12.],
        [ 1.,  0., 15.]])

In [0]:
#원서 51
from sklearn.preprocessing import Imputer
data=np.array([[1, np.nan, 2],[2, 3, np.nan], [-1, 4, 2]])

In [60]:
imp=Imputer(strategy='mean')
imp.fit_transform(data)

array([[ 1. ,  3.5,  2. ],
       [ 2. ,  3. ,  2. ],
       [-1. ,  4. ,  2. ]])

In [62]:
imp=Imputer(strategy='median')
imp.fit_transform(data)

array([[ 1. ,  3.5,  2. ],
       [ 2. ,  3. ,  2. ],
       [-1. ,  4. ,  2. ]])

In [63]:
imp=Imputer(strategy='most_frequent')
imp.fit_transform(data)

array([[ 1.,  3.,  2.],
       [ 2.,  3.,  2.],
       [-1.,  4.,  2.]])

In [0]:
from sklearn.preprocessing import StandardScaler

data = [[0, 0], [3, 0], [1, 1], [2, 1], [5, -5], [10, 0]]
ss=StandardScaler()
scaled_data=ss.fit_transform(data)

In [75]:
scaled_data

array([[-1.05930987,  0.24253563],
       [-0.15132998,  0.24253563],
       [-0.75664991,  0.72760688],
       [-0.45398995,  0.72760688],
       [ 0.45398995, -2.18282063],
       [ 1.96728976,  0.24253563]])

In [0]:
#원서 53
from sklearn.preprocessing import RobustScaler
rb1=RobustScaler(quantile_range=(15, 85))
scaled_data1=rb1.fit_transform(data)

rb1=RobustScaler(quantile_range=(25, 75))
scaled_data1=rb1.fit_transform(data)

rb2=RobustScaler(quantile_range=(30, 60))
scaled_data2=rb2.fit_transform(data)

In [79]:
#원서 54 : 정규화 예제
from sklearn.preprocessing import Normalizer
data=np.array([1.0, 2.0])
n_max=Normalizer(norm='max')
n_max.fit_transform(data.reshape(1, -1))

array([[0.5, 1. ]])

In [80]:
n_11=Normalizer(norm='l1')
n_11.fit_transform(data.reshape(1, -1))

array([[0.33333333, 0.66666667]])

In [82]:
n_12=Normalizer(norm='l2')
n_12.fit_transform(data.reshape(1,-1))

array([[0.4472136 , 0.89442719]])